import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedUser64Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle24Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/Generated\$5000Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedCoachWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedCarpenterWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedFugas2Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedPainterWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedActorressWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedInfoWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedCourierWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle70Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle71Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle69Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle63Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle59Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle68Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle65Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedBuilderWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedPlumberWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedPsicologistWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedCATEGORIESWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle53Widget6.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedHome14Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedBakerWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedTeacherWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle67Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle64Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle66Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedSingerWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle72Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle53Widget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedRectangle62Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedFiltersWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax20widget/generated/GeneratedConsuelorWidget2.dart';

/* Frame iPhone 11 Pro Max - 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle53Widget5(),
              ),
              Positioned(
                left: 60.0,
                top: 767.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle54Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget(),
              ),
              Positioned(
                left: 234.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedNameWidget1(),
              ),
              Positioned(
                left: 94.0,
                top: 781.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 686.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedFugas2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -50.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 783.0,
                child: GeneratedRectangle53Widget6(),
              ),
              Positioned(
                left: 102.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 47.0,
                child: GeneratedCATEGORIESWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 569.0,
                child: GeneratedRectangle24Widget4(),
              ),
              Positioned(
                left: 354.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget3(),
              ),
              Positioned(
                left: 181.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 23.0,
                child: GeneratedFiltersWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome14Widget3(),
              ),
              Positioned(
                left: 362.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser64Widget3(),
              ),
              Positioned(
                left: 201.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle59Widget2(),
              ),
              Positioned(
                left: 69.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle62Widget2(),
              ),
              Positioned(
                left: 96.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle63Widget2(),
              ),
              Positioned(
                left: 110.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 26.0,
                child: GeneratedPsicologistWidget2(),
              ),
              Positioned(
                left: 95.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedPlumberWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle64Widget2(),
              ),
              Positioned(
                left: 264.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedBakerWidget2(),
              ),
              Positioned(
                left: 227.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedTeacherWidget2(),
              ),
              Positioned(
                left: 201.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle65Widget2(),
              ),
              Positioned(
                left: 69.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle66Widget2(),
              ),
              Positioned(
                left: 96.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle67Widget2(),
              ),
              Positioned(
                left: 124.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCourierWidget2(),
              ),
              Positioned(
                left: 105.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedSingerWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle68Widget2(),
              ),
              Positioned(
                left: 247.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCarpenterWidget2(),
              ),
              Positioned(
                left: 232.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedBuilderWidget2(),
              ),
              Positioned(
                left: 201.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle69Widget2(),
              ),
              Positioned(
                left: 69.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle70Widget2(),
              ),
              Positioned(
                left: 96.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle71Widget2(),
              ),
              Positioned(
                left: 124.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCoachWidget2(),
              ),
              Positioned(
                left: 90.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 26.0,
                child: GeneratedConsuelorWidget2(),
              ),
              Positioned(
                left: 230.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle72Widget2(),
              ),
              Positioned(
                left: 247.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 26.0,
                child: GeneratedActorressWidget2(),
              ),
              Positioned(
                left: 232.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedPainterWidget2(),
              ),
              Positioned(
                left: 202.0,
                top: 867.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget4(),
              )
            ]),
      ),
    ));
  }
}
