import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedNAMEWidget8.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle28Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedEllipse16Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle31Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedSENDMESSAGEWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax11widget/generated/GeneratedRectangle24Widget10.dart';

/* Frame iPhone 11 Pro Max - 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 414.0,
          height: 896.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 216, 160, 125),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 5.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 110.0,
                  child: GeneratedRectangle55Widget1(),
                ),
                Positioned(
                  left: 20.0,
                  top: 218.0,
                  right: null,
                  bottom: null,
                  width: 340.0,
                  height: 88.0,
                  child: GeneratedRectangle28Widget3(),
                ),
                Positioned(
                  left: 393.0,
                  top: 440.0,
                  right: null,
                  bottom: null,
                  width: 331.0,
                  height: 88.0,
                  child: GeneratedRectangle36Widget(),
                ),
                Positioned(
                  left: 393.0,
                  top: 551.0,
                  right: null,
                  bottom: null,
                  width: 331.0,
                  height: 88.0,
                  child: GeneratedRectangle37Widget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 329.0,
                  right: null,
                  bottom: null,
                  width: 340.0,
                  height: 88.0,
                  child: GeneratedRectangle35Widget(),
                ),
                Positioned(
                  left: 20.0,
                  top: 852.0,
                  right: null,
                  bottom: null,
                  width: 373.0,
                  height: 67.0,
                  child: GeneratedRectangle31Widget3(),
                ),
                Positioned(
                  left: 41.0,
                  top: 807.0,
                  right: null,
                  bottom: null,
                  width: 151.0,
                  height: 23.0,
                  child: GeneratedSENDMESSAGEWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 414.0,
                  height: 63.0,
                  child: GeneratedRectangle24Widget10(),
                ),
                Positioned(
                  left: 14.0,
                  top: 8.0,
                  right: null,
                  bottom: null,
                  width: 48.0,
                  height: 47.0,
                  child: GeneratedRectangle34Widget(),
                ),
                Positioned(
                  left: 79.0,
                  top: 37.0,
                  right: null,
                  bottom: null,
                  width: 44.0,
                  height: 46.0,
                  child: GeneratedEllipse16Widget1(),
                ),
                Positioned(
                  left: 147.0,
                  top: 47.0,
                  right: null,
                  bottom: null,
                  width: 141.0,
                  height: 30.0,
                  child: GeneratedNAMEWidget8(),
                ),
                Positioned(
                  left: 330.0,
                  top: 792.0,
                  right: null,
                  bottom: null,
                  width: 54.0,
                  height: 52.0,
                  child: GeneratedEllipse21Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
