import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedLapiz1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle58Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedAboutmeWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedBotondeplay2Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedFreepikCharacterinject230Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedHome1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedCertificatesWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedWhoareyouWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedNAMEWidget12.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedEllipse14Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle59Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle57Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedEdit12Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedCONTACTWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle32Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedBotondeplay1Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget9.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedUser71Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedRectangle54Widget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedCertification1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedCurrentServicesWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax15widget/generated/GeneratedEllipse23Widget.dart';

/* Frame iPhone 11 Pro Max - 15
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax15Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -17.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 431.0,
                height: 793.0,
                child: GeneratedRectangle54Widget5(),
              ),
              Positioned(
                left: 9.0,
                top: 878.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 628.0,
                child: GeneratedRectangle32Widget3(),
              ),
              Positioned(
                left: 24.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 46.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 48.0,
                child: GeneratedRectangle60Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 740.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 44.0,
                child: GeneratedRectangle61Widget(),
              ),
              Positioned(
                left: 287.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 46.0,
                child: GeneratedRectangle59Widget3(),
              ),
              Positioned(
                left: 152.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 46.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 105.0,
                child: GeneratedEllipse14Widget2(),
              ),
              Positioned(
                left: 224.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: GeneratedNAMEWidget12(),
              ),
              Positioned(
                left: 217.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCONTACTWidget2(),
              ),
              Positioned(
                left: 118.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 158.0,
                height: 44.0,
                child: GeneratedAboutmeWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.12077294685990338;

                  final double height =
                      constraints.maxHeight * 0.05580357142857143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.821256038647343,
                        y: constraints.maxHeight * 0.15401785714285715,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUser71Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4758454106280193;

                  final double height =
                      constraints.maxHeight * 0.25558035714285715;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.007246376811594203,
                        y: constraints.maxHeight * 0.056919642857142856,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikCharacterinject230Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 233.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 67.0,
                child: GeneratedEllipse23Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 34.0,
                child: GeneratedLapiz1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 60.0,
                child: GeneratedRectangle57Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 23.0,
                child: GeneratedWhoareyouWidget(),
              ),
              Positioned(
                left: 374.0,
                top: 198.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedEdit12Widget(),
              ),
              Positioned(
                left: 135.0,
                top: 481.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 34.0,
                child: GeneratedCurrentServicesWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 35.0,
                child: GeneratedCertificatesWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 818.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget9(),
              ),
              Positioned(
                left: 340.0,
                top: 682.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBotondeplay1Widget(),
              ),
              Positioned(
                left: 340.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedBotondeplay2Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 18.0,
                child: GeneratedCertification1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.11594202898550725;

                  final double height =
                      constraints.maxHeight * 0.052455357142857144;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8454106280193237,
                        y: constraints.maxHeight * 0.008928571428571428,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle58Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 31.0,
                child: GeneratedHome1Widget(),
              )
            ]),
      ),
    ));
  }
}
