import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedChatcuate1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle31Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle36Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle28Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle55Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedFreepikEmojisinject138Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle34Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedEllipse16Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedNAMEWidget9.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle24Widget11.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedSENDMESSAGEWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedEllipse21Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax17widget/generated/GeneratedRectangle37Widget1.dart';

/* Frame iPhone 11 Pro Max - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0024156063651117;

                  final double height =
                      constraints.maxHeight * 0.6065126827784947;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.016908212560386472,
                        y: constraints.maxHeight * 0.17410714285714285,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikEmojisinject138Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -219.0,
                top: 376.38800048828125,
                right: null,
                bottom: null,
                width: 504.19677734375,
                height: 794.60595703125,
                child: GeneratedChatcuate1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 5.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedRectangle55Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 88.0,
                child: GeneratedRectangle28Widget4(),
              ),
              Positioned(
                left: 393.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 88.0,
                child: GeneratedRectangle36Widget1(),
              ),
              Positioned(
                left: 393.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 88.0,
                child: GeneratedRectangle37Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 88.0,
                child: GeneratedRectangle35Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 67.0,
                child: GeneratedRectangle31Widget4(),
              ),
              Positioned(
                left: 41.0,
                top: 807.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 23.0,
                child: GeneratedSENDMESSAGEWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 63.0,
                child: GeneratedRectangle24Widget11(),
              ),
              Positioned(
                left: 14.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 47.0,
                child: GeneratedRectangle34Widget1(),
              ),
              Positioned(
                left: 79.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 46.0,
                child: GeneratedEllipse16Widget2(),
              ),
              Positioned(
                left: 147.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 141.0,
                height: 30.0,
                child: GeneratedNAMEWidget9(),
              ),
              Positioned(
                left: 330.0,
                top: 792.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 52.0,
                child: GeneratedEllipse21Widget1(),
              )
            ]),
      ),
    ));
  }
}
