import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle29Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedMESSAGEINFORMATIONWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedEllipse15Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle24Widget8.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedLupa2Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget7.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedMESSAGEINFORMATIONWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedNAMEWidget7.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedUser65Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedHome15Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedEllipse17Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedNAMEWidget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedMESSAGEINFORMATIONWidget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedMESSAGEINFORMATIONWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedNAMEWidget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle30Widget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle24Widget9.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedNAMEWidget6.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle53Widget9.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedMESSAGESWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax10widget/generated/GeneratedRectangle31Widget2.dart';

/* Frame iPhone 11 Pro Max - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 221.0,
                child: GeneratedRectangle53Widget9(),
              ),
              Positioned(
                left: 21.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 86.0,
                child: GeneratedRectangle28Widget2(),
              ),
              Positioned(
                left: 202.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedNAMEWidget4(),
              ),
              Positioned(
                left: 21.0,
                top: 502.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 87.0,
                child: GeneratedRectangle29Widget2(),
              ),
              Positioned(
                left: 202.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedNAMEWidget5(),
              ),
              Positioned(
                left: 21.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 87.0,
                child: GeneratedRectangle30Widget5(),
              ),
              Positioned(
                left: 202.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 28.0,
                child: GeneratedNAMEWidget6(),
              ),
              Positioned(
                left: 21.0,
                top: 717.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 86.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: 202.0,
                top: 647.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 27.0,
                child: GeneratedNAMEWidget7(),
              ),
              Positioned(
                left: 127.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 23.0,
                child: GeneratedMESSAGEINFORMATIONWidget(),
              ),
              Positioned(
                left: 127.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 23.0,
                child: GeneratedMESSAGEINFORMATIONWidget1(),
              ),
              Positioned(
                left: 127.0,
                top: 456.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 23.0,
                child: GeneratedMESSAGEINFORMATIONWidget2(),
              ),
              Positioned(
                left: 127.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 240.0,
                height: 23.0,
                child: GeneratedMESSAGEINFORMATIONWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 178.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle24Widget8(),
              ),
              Positioned(
                left: 48.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedLupa2Widget1(),
              ),
              Positioned(
                left: -1.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 63.0,
                child: GeneratedRectangle24Widget9(),
              ),
              Positioned(
                left: 113.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 47.0,
                child: GeneratedMESSAGESWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedEllipse15Widget1(),
              ),
              Positioned(
                left: 33.0,
                top: 426.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 532.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 638.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedEllipse18Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 862.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget7(),
              ),
              Positioned(
                left: 27.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome15Widget(),
              ),
              Positioned(
                left: 364.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser65Widget(),
              )
            ]),
      ),
    ));
  }
}
