import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle54Widget7.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle36Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle35Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedUser66Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle37Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle33Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedSELECTWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedLupa2Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/Generated1573658897_566202_1573659544_noticia_normal1Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedHome16Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedFiltersWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedMAPWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax22widget/generated/GeneratedRectangle24Widget12.dart';

/* Frame iPhone 11 Pro Max - 22
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax22Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 219.0,
                child: GeneratedRectangle54Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 66.0,
                child: GeneratedRectangle35Widget3(),
              ),
              Positioned(
                left: 162.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 46.0,
                child: GeneratedMAPWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 50.0,
                child: GeneratedRectangle36Widget2(),
              ),
              Positioned(
                left: 15.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 527.0,
                child: GeneratedRectangle37Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedLupa2Widget2(),
              ),
              Positioned(
                left: 316.0,
                top: 145.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 30.0,
                child: GeneratedRectangle24Widget12(),
              ),
              Positioned(
                left: 328.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 58.0,
                height: 32.0,
                child: GeneratedFiltersWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle33Widget2(),
              ),
              Positioned(
                left: 163.0,
                top: 825.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 33.0,
                child: GeneratedSELECTWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 534.0,
                child:
                    Generated1573658897_566202_1573659544_noticia_normal1Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome16Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser66Widget(),
              )
            ]),
      ),
    ));
  }
}
