import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/Generated\$5000Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFontanero1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedPasearalperro11Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFlechahaciaabajoparanavegar1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedNameWidget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedPintor1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedLibros11Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedNameWidget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedUser62Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedSERVICESWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFugas1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFilterWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedInfoWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedInfoWidget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedSEARCHWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle52Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFlechahaciaabajoparanavegar3Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedConstruction1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedHome12Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/Generated\$5000Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedLupa1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedFlechahaciaabajoparanavegar2Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax4widget/generated/GeneratedRectangle17Widget.dart';

/* Frame iPhone 11 Pro Max - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -18.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 226.0,
                child: GeneratedRectangle52Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 31.0,
                child: GeneratedSERVICESWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 138.0001220703125,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 52.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 252.00006103515625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 115.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 108.0,
                top: 252.00006103515625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 115.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 194.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 115.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 252.00006103515625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 115.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 366.0,
                top: 253.00006103515625,
                right: null,
                bottom: null,
                width: 17.0,
                height: 115.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 252.00006103515625,
                right: null,
                bottom: null,
                width: 79.0,
                height: 115.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 296.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 30.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedLupa1Widget(),
              ),
              Positioned(
                left: 307.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 23.0,
                child: GeneratedFilterWidget1(),
              ),
              Positioned(
                left: 354.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar1Widget(),
              ),
              Positioned(
                left: 372.0,
                top: 314.00006103515625,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar2Widget(),
              ),
              Positioned(
                left: 216.0,
                top: 871.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar3Widget(),
              ),
              Positioned(
                left: 222.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget2(),
              ),
              Positioned(
                left: 226.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedNameWidget3(),
              ),
              Positioned(
                left: 86.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget2(),
              ),
              Positioned(
                left: 55.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 225.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget3(),
              ),
              Positioned(
                left: 229.0,
                top: 716.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedNameWidget4(),
              ),
              Positioned(
                left: 89.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget3(),
              ),
              Positioned(
                left: 133.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 142.0,
                height: 47.0,
                child: GeneratedSEARCHWidget(),
              ),
              Positioned(
                left: 203.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 60.0,
                child: GeneratedConstruction1Widget(),
              ),
              Positioned(
                left: 116.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedLibros11Widget(),
              ),
              Positioned(
                left: 27.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedPintor1Widget(),
              ),
              Positioned(
                left: 285.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedPasearalperro11Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 64.0,
                child: GeneratedFontanero1Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedFugas1Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome12Widget(),
              ),
              Positioned(
                left: 359.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser62Widget(),
              )
            ]),
      ),
    ));
  }
}
