import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedREQUESTSWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedHome12Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedNameWidget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedFontanero1Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/Generated\$5000Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedRectangle52Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/Generated\$5000Widget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedNameWidget6.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedInfoWidget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedInfoWidget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedUser62Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedFlechahaciaabajoparanavegar3Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax25widget/generated/GeneratedFugas1Widget1.dart';

/* Frame iPhone 11 Pro Max - 25
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax25Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -18.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 226.0,
                child: GeneratedRectangle52Widget3(),
              ),
              Positioned(
                left: 27.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle22Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 285.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle20Widget1(),
              ),
              Positioned(
                left: 52.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle21Widget1(),
              ),
              Positioned(
                left: 216.0,
                top: 871.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar3Widget1(),
              ),
              Positioned(
                left: 222.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget4(),
              ),
              Positioned(
                left: 226.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedNameWidget5(),
              ),
              Positioned(
                left: 86.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget4(),
              ),
              Positioned(
                left: 55.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle23Widget1(),
              ),
              Positioned(
                left: 225.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget5(),
              ),
              Positioned(
                left: 229.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 26.0,
                child: GeneratedNameWidget6(),
              ),
              Positioned(
                left: 89.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget5(),
              ),
              Positioned(
                left: 133.0,
                top: 62.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 47.0,
                child: GeneratedREQUESTSWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 64.0,
                child: GeneratedFontanero1Widget1(),
              ),
              Positioned(
                left: 73.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedFugas1Widget1(),
              ),
              Positioned(
                left: 22.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome12Widget1(),
              ),
              Positioned(
                left: 359.0,
                top: 19.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser62Widget1(),
              )
            ]),
      ),
    ));
  }
}
