import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedIdWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedPeoplecelebratingThaipusamfestivalcuate1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedLoginWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedLogo52Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedPolygon4Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedPolygon3Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedFreepikbackgroundcompleteinject14Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedFondoborroso15360x6401Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax1widget/generated/GeneratedRectangle2Widget1.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 425.0,
        height: 886.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -4.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 429.0,
                height: 422.0,
                child: GeneratedRectangle44Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.3101808076746324;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 556.8268432617188;

                  double percentHeight = 0.8649340214094243;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 766.33154296875;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 1.8081120749080883,
                        translateY: constraints.maxHeight * 1.1181453937332464,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedPolygon4Widget())
                  ]);
                }),
              ),
              Positioned(
                left: -35.48716735839844,
                top: 685.05908203125,
                right: null,
                bottom: null,
                width: 510.53179931640625,
                height: 503.969970703125,
                child: GeneratedPolygon3Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 820.0,
                child: GeneratedFondoborroso15360x6401Widget(),
              ),
              Positioned(
                left: -51.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 527.0,
                height: 809.0,
                child:
                    GeneratedPeoplecelebratingThaipusamfestivalcuate1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 1.0203033088235294;

                  final double height =
                      constraints.maxHeight * 0.2048078239905915;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.020356234382180607,
                        y: constraints.maxHeight * 0.055304740406320545,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              GeneratedFreepikbackgroundcompleteinject14Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 41.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 42.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 43.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 39.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 26.0,
                child: GeneratedIdWidget1(),
              ),
              Positioned(
                left: 47.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 46.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 26.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 175.0,
                top: 748.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 30.0,
                child: GeneratedLoginWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 76.0,
                child: GeneratedLogo52Widget(),
              )
            ]),
      ),
    ));
  }
}
