import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedRectangle35Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedRectangle54Widget6.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedMAPWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedRectangle37Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/GeneratedSELECTWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax12widget/generated/Generated1573658897_566202_1573659544_noticia_normal1Widget.dart';

/* Frame iPhone 11 Pro Max - 12
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax12Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 134.0,
                child: GeneratedRectangle54Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 66.0,
                child: GeneratedRectangle35Widget2(),
              ),
              Positioned(
                left: 162.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 46.0,
                child: GeneratedMAPWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 247.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 527.0,
                child: GeneratedRectangle37Widget2(),
              ),
              Positioned(
                left: 27.0,
                top: 810.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle33Widget1(),
              ),
              Positioned(
                left: 163.0,
                top: 825.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 33.0,
                child: GeneratedSELECTWidget1(),
              ),
              Positioned(
                left: 15.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 628.0,
                child:
                    Generated1573658897_566202_1573659544_noticia_normal1Widget(),
              )
            ]),
      ),
    ));
  }
}
