import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle53Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedTeacherWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedUser64Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedADDWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle72Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle67Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedHome14Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedPlumberWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle30Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedActorressWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedADDSERVICEWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedCATEGORYWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedSingerWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle69Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedPsicologistWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedBakerWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedConsuelorWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedPainterWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedCATEGORYWidget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedCourierWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle59Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle70Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedCarpenterWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedBuilderWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedRectangle65Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax19widget/generated/GeneratedCoachWidget.dart';

/* Frame iPhone 11 Pro Max - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -50.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 783.0,
                child: GeneratedRectangle53Widget3(),
              ),
              Positioned(
                left: 97.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 44.0,
                child: GeneratedADDSERVICEWidget2(),
              ),
              Positioned(
                left: 28.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 569.0,
                child: GeneratedRectangle24Widget2(),
              ),
              Positioned(
                left: 354.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget1(),
              ),
              Positioned(
                left: 156.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: GeneratedCATEGORYWidget2(),
              ),
              Positioned(
                left: 156.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: GeneratedCATEGORYWidget3(),
              ),
              Positioned(
                left: 28.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle30Widget2(),
              ),
              Positioned(
                left: 183.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedADDWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome14Widget1(),
              ),
              Positioned(
                left: 362.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser64Widget1(),
              ),
              Positioned(
                left: 201.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle59Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle62Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle63Widget(),
              ),
              Positioned(
                left: 110.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 26.0,
                child: GeneratedPsicologistWidget(),
              ),
              Positioned(
                left: 95.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedPlumberWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle64Widget(),
              ),
              Positioned(
                left: 264.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedBakerWidget(),
              ),
              Positioned(
                left: 227.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedTeacherWidget(),
              ),
              Positioned(
                left: 201.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle65Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle66Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle67Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCourierWidget(),
              ),
              Positioned(
                left: 105.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedSingerWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle68Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCarpenterWidget(),
              ),
              Positioned(
                left: 232.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedBuilderWidget(),
              ),
              Positioned(
                left: 201.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle69Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle70Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle71Widget(),
              ),
              Positioned(
                left: 124.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCoachWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 26.0,
                child: GeneratedConsuelorWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle72Widget(),
              ),
              Positioned(
                left: 247.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 26.0,
                child: GeneratedActorressWidget(),
              ),
              Positioned(
                left: 232.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedPainterWidget(),
              )
            ]),
      ),
    ));
  }
}
