import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedRectangle53Widget10.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedRectangle57Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedRectangle54Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget8.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedRectangle32Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedInfoWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedEllipse14Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/Generated\$5000Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedFugas2Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedRectangle54Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedGeneralInfoWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedUser32Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedUser71Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedCONTACTWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax16widget/generated/GeneratedNAMEWidget11.dart';

/* Frame iPhone 11 Pro Max - 16
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax16Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -11.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 436.0,
                height: 744.0,
                child: GeneratedRectangle54Widget3(),
              ),
              Positioned(
                left: 11.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 612.0,
                child: GeneratedRectangle32Widget2(),
              ),
              Positioned(
                left: 11.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 78.0,
                child: GeneratedEllipse14Widget1(),
              ),
              Positioned(
                left: 92.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: GeneratedNAMEWidget11(),
              ),
              Positioned(
                left: 70.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCONTACTWidget1(),
              ),
              Positioned(
                left: 109.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 44.0,
                child: GeneratedGeneralInfoWidget(),
              ),
              Positioned(
                left: 361.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser32Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.12077294685990338;

                  final double height =
                      constraints.maxHeight * 0.05580357142857143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06280193236714976,
                        y: constraints.maxHeight * 0.140625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUser71Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 28.0,
                top: 644.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 185.0,
                child: GeneratedRectangle53Widget10(),
              ),
              Positioned(
                left: 203.0,
                top: 852.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget8(),
              ),
              Positioned(
                left: 56.0,
                top: 746.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 50.0,
                child: GeneratedRectangle54Widget4(),
              ),
              Positioned(
                left: 221.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: Generated$5000Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 26.0,
                child: GeneratedInfoWidget1(),
              ),
              Positioned(
                left: 74.0,
                top: 665.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedFugas2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.11594202898550725;

                  final double height =
                      constraints.maxHeight * 0.052455357142857144;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.026570048309178744,
                        y: constraints.maxHeight * 0.016741071428571428,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle57Widget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
