import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedDESCRIPTIONWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedRectangle44Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedUser61Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedEllipse22Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedFreepikcharacter5inject5Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedREQUESTWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedHome11Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedFreepikDeskinject5Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedArrow2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedSunmontuewedthufrisat1234567891011121314151617181920212.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedMarchWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedREQUESTWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax3widget/generated/GeneratedFreepikcharacter3inject5Widget.dart';

/* Frame iPhone 11 Pro Max - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -18.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 215.0,
                child: GeneratedRectangle52Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 323.0,
                child: GeneratedRectangle44Widget1(),
              ),
              Positioned(
                left: 133.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 47.0,
                child: GeneratedREQUESTWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3115942028985507;

                  final double height =
                      constraints.maxHeight * 0.21835759707859584;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04830917874396135,
                        y: constraints.maxHeight * 0.7868303571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter3inject5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4758454106280193;

                  final double height =
                      constraints.maxHeight * 0.10539061682564872;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20048309178743962,
                        y: constraints.maxHeight * 0.8984375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikDeskinject5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.40579702773531856;

                  final double height =
                      constraints.maxHeight * 0.19409748486110143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5603864734299517,
                        y: constraints.maxHeight * 0.8180803571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter5inject5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 109.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 48.0,
                child: GeneratedRectangle45Widget(),
              ),
              Positioned(
                left: 174.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 23.0,
                child: GeneratedREQUESTWidget1(),
              ),
              Positioned(
                left: 261.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 0.0,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 163.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 0.0,
                child: GeneratedArrow2Widget(),
              ),
              Positioned(
                left: 191.0,
                top: 395.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 32.0,
                child: GeneratedMarchWidget(),
              ),
              Positioned(
                left: 247.0,
                top: 562.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 37.0,
                child: GeneratedEllipse22Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 200.0,
                child:
                    GeneratedSunmontuewedthufrisat1234567891011121314151617181920212(),
              ),
              Positioned(
                left: 35.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 158.0,
                child: GeneratedRectangle43Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: GeneratedDESCRIPTIONWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome11Widget(),
              ),
              Positioned(
                left: 353.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser61Widget(),
              )
            ]),
      ),
    ));
  }
}
