import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedADDWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedUser64Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle73Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedCATEGORYWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedCATEGORYWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedUploadimagesWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedLocationWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedPriceWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedDescriptionWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedHome14Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedDescriptionWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedUpload1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedADDSERVICEWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax5widget/generated/GeneratedRectangle24Widget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -50.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 254.0,
                child: GeneratedRectangle53Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 44.0,
                child: GeneratedADDSERVICEWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 354.0,
                top: 156.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: GeneratedCATEGORYWidget(),
              ),
              Positioned(
                left: 156.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 23.0,
                child: GeneratedCATEGORYWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 33.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 52.0,
                top: 303.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 33.0,
                child: GeneratedPriceWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 50.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 33.0,
                child: GeneratedLocationWidget(),
              ),
              Positioned(
                left: 186.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedADDWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 166.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 370.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 166.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 33.0,
                child: GeneratedDescriptionWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 33.0,
                child: GeneratedDescriptionWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 65.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 320.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUpload1Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 30.0,
                child: GeneratedUploadimagesWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome14Widget(),
              ),
              Positioned(
                left: 362.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser64Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle73Widget(),
              ),
              Positioned(
                left: 301.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedSearchWidget(),
              )
            ]),
      ),
    ));
  }
}
