import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedSigninWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedLogo51Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedFondoborroso15360x6401Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedLivecollaborationamico1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax13widget/generated/GeneratedCreateAccountWidget1.dart';

/* Frame iPhone 11 Pro Max - 13
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax13Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 425.0,
        height: 886.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 29.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 820.0,
                child: GeneratedFondoborroso15360x6401Widget1(),
              ),
              Positioned(
                left: 48.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 67.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 51.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 67.0,
                child: GeneratedRectangle39Widget1(),
              ),
              Positioned(
                left: 183.0,
                top: 691.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 30.0,
                child: GeneratedSigninWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 791.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 30.0,
                child: GeneratedCreateAccountWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 257.0,
                right: null,
                bottom: null,
                width: 371.0,
                height: 372.0,
                child: GeneratedLivecollaborationamico1Widget(),
              ),
              Positioned(
                left: 85.0,
                top: 78.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 76.0,
                child: GeneratedLogo51Widget(),
              )
            ]),
      ),
    ));
  }
}
