import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatedframe1widget/generated/GeneratedResume11Widget.dart';
import 'package:flutterapp/diakoniaapp/generatedframe1widget/generated/GeneratedPlus1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatedframe1widget/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/diakoniaapp/generatedframe1widget/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/diakoniaapp/generatedframe1widget/generated/GeneratedUser21Widget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 368.0,
          height: 823.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 116.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 92.0,
                  height: 98.0,
                  child: GeneratedPlus1Widget(),
                ),
                Positioned(
                  left: 105.0,
                  top: 287.0,
                  right: null,
                  bottom: null,
                  width: 114.0,
                  height: 99.0,
                  child: GeneratedResume11Widget(),
                ),
                Positioned(
                  left: 100.0,
                  top: 567.0,
                  right: null,
                  bottom: null,
                  width: 123.0,
                  height: 123.0,
                  child: GeneratedImage4Widget(),
                ),
                Positioned(
                  left: 94.0,
                  top: 126.0,
                  right: null,
                  bottom: null,
                  width: 136.0,
                  height: 136.0,
                  child: GeneratedImage5Widget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 411.0,
                  right: null,
                  bottom: null,
                  width: 128.0,
                  height: 128.0,
                  child: GeneratedUser21Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
