import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedFreepikcharacter2inject128Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle24Widget6.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedFreepikcharacter5inject128Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedDescriptionWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle24Widget5.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedNameWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle27Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle53Widget7.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle30Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedPhoneWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedIdWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedCertificatetitleWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedLastnameWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedUpload1Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedPROFILEWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedSAVEWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedRectangle54Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedUploadcertificationWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax7widget/generated/GeneratedEdit11Widget.dart';

/* Frame iPhone 11 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5895707872178819;

                  final double height =
                      constraints.maxHeight * 0.21874993188040598;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.4492753623188406,
                        y: constraints.maxHeight * 0.7734375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter5inject128Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.49315488511237543;

                  final double height =
                      constraints.maxHeight * 0.23812832151140487;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * -0.036231884057971016,
                        y: constraints.maxHeight * 0.7589285714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter2inject128Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: -4.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 257.0,
                child: GeneratedRectangle53Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 63.0,
                child: GeneratedRectangle24Widget5(),
              ),
              Positioned(
                left: 133.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 47.0,
                child: GeneratedPROFILEWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle25Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 336.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle27Widget1(),
              ),
              Positioned(
                left: 39.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 33.0,
                child: GeneratedNameWidget2(),
              ),
              Positioned(
                left: 49.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 112.0,
                height: 33.0,
                child: GeneratedLastnameWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 33.0,
                child: GeneratedIdWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 543.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 50.0,
                child: GeneratedRectangle54Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 33.0,
                child: GeneratedPhoneWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 773.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle30Widget3(),
              ),
              Positioned(
                left: 170.0,
                top: 796.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 33.0,
                child: GeneratedSAVEWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 623.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 33.0,
                child: GeneratedDescriptionWidget2(),
              ),
              Positioned(
                left: 18.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 65.0,
                child: GeneratedRectangle24Widget6(),
              ),
              Positioned(
                left: 320.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUpload1Widget1(),
              ),
              Positioned(
                left: 52.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 30.0,
                child: GeneratedUploadcertificationWidget(),
              ),
              Positioned(
                left: 138.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 144.0,
                child: GeneratedEllipse15Widget(),
              ),
              Positioned(
                left: 257.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedEdit11Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 31.0,
                child: GeneratedCertificatetitleWidget(),
              )
            ]),
      ),
    ));
  }
}
