import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedSUCCESFULREQUESTWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedFreepikcharacter3inject5Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedRectangle45Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedACCEPTWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedREQUESTWidget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedFreepikDeskinject5Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedFreepikcharacter5inject5Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedRectangle44Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax18widget/generated/GeneratedRectangle52Widget1.dart';

/* Frame iPhone 11 Pro Max - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -18.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 215.0,
                child: GeneratedRectangle52Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 284.0,
                child: GeneratedRectangle44Widget2(),
              ),
              Positioned(
                left: 133.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 47.0,
                child: GeneratedREQUESTWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.3115942028985507;

                  final double height =
                      constraints.maxHeight * 0.21835759707859584;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.04830917874396135,
                        y: constraints.maxHeight * 0.7868303571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter3inject5Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4758454106280193;

                  final double height =
                      constraints.maxHeight * 0.10539061682564872;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.20048309178743962,
                        y: constraints.maxHeight * 0.8984375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikDeskinject5Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 109.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 48.0,
                child: GeneratedRectangle45Widget1(),
              ),
              Positioned(
                left: 174.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 23.0,
                child: GeneratedACCEPTWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.40579702773531856;

                  final double height =
                      constraints.maxHeight * 0.19409748486110143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5603864734299517,
                        y: constraints.maxHeight * 0.8180803571428571,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFreepikcharacter5inject5Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 119.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 23.0,
                child: GeneratedSUCCESFULREQUESTWidget(),
              )
            ]),
      ),
    ));
  }
}
