import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedPolygon6Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedCreateyouraccountWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedPolygon5Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedIdWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedPolygon8Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedPolygon7Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax9widget/generated/GeneratedLogo31Widget.dart';

/* Frame iPhone 11 Pro Max - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1608.5915222167969,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 425.0,
                      height: 898.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -5.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 243.0,
                              height: 158.0,
                              child: GeneratedRectangle39Widget(),
                            ),
                            Positioned(
                              left: -5.223114013671875,
                              top: 399.0590515136719,
                              right: null,
                              bottom: null,
                              width: 486.3119812011719,
                              height: 450.2693786621094,
                              child: GeneratedPolygon7Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 1.1726726935891545;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        498.3858947753906;

                                double percentHeight = 0.532135145701385;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        477.85736083984375;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          1.111959228515625,
                                      translateY: constraints.maxHeight *
                                          0.7156426444616509,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedPolygon5Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 1.1726724063648897;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        498.3857727050781;

                                double percentHeight = 0.532135179685325;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        477.8573913574219;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          1.1297710104549632,
                                      translateY: constraints.maxHeight *
                                          1.2591694107565423,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedPolygon6Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: -20.223114013671875,
                              top: 898.05908203125,
                              right: null,
                              bottom: null,
                              width: 485.42181396484375,
                              height: 476.2115173339844,
                              child: GeneratedPolygon8Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 301.0,
                              right: null,
                              bottom: null,
                              width: 168.0,
                              height: 23.0,
                              child: GeneratedCreateyouraccountWidget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 352.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 42.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 414.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 42.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 475.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 42.0,
                              child: GeneratedRectangle4Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 615.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 67.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 363.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 26.0,
                              child: GeneratedIdWidget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 425.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 26.0,
                              child: GeneratedPasswordWidget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 23.0,
                              child: GeneratedConfirmPasswordWidget(),
                            ),
                            Positioned(
                              left: 159.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 30.0,
                              child: GeneratedSignUpWidget(),
                            ),
                            Positioned(
                              left: 78.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child: GeneratedLogo31Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.11294117647058824;

                                final double height = constraints.maxHeight *
                                    0.052338530066815145;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.07058823529411765,
                                      y: constraints.maxHeight *
                                          0.9164810690423163,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedRectangle57Widget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
