import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedFiltersWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle65Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle67Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle68Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle72Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedActorressWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedSingerWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedBakerWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedBuilderWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle63Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle59Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedHome14Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedSELECTWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedCourierWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedPlumberWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedFlechahaciaabajoparanavegar4Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle64Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedUser64Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedMAPWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedConsuelorWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle69Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle62Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/Generated1573658897_566202_1573659544_noticia_normal2Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle71Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedCarpenterWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle53Widget4.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedTeacherWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle70Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle66Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedPainterWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedCoachWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedPsicologistWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax23widget/generated/GeneratedRectangle55Widget.dart';

/* Frame iPhone 11 Pro Max - 23
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax23Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(178, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 14.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 386.0,
                height: 534.0,
                child:
                    Generated1573658897_566202_1573659544_noticia_normal2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -50.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 783.0,
                child: GeneratedRectangle53Widget4(),
              ),
              Positioned(
                left: 168.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 47.0,
                child: GeneratedMAPWidget(),
              ),
              Positioned(
                left: 28.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 569.0,
                child: GeneratedRectangle24Widget3(),
              ),
              Positioned(
                left: 354.0,
                top: 166.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedFlechahaciaabajoparanavegar4Widget2(),
              ),
              Positioned(
                left: 190.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 23.0,
                child: GeneratedFiltersWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedHome14Widget2(),
              ),
              Positioned(
                left: 362.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser64Widget2(),
              ),
              Positioned(
                left: 201.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle59Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 226.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle62Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle63Widget1(),
              ),
              Positioned(
                left: 110.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 26.0,
                child: GeneratedPsicologistWidget1(),
              ),
              Positioned(
                left: 95.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedPlumberWidget1(),
              ),
              Positioned(
                left: 230.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle64Widget1(),
              ),
              Positioned(
                left: 264.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedBakerWidget1(),
              ),
              Positioned(
                left: 227.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 26.0,
                child: GeneratedTeacherWidget1(),
              ),
              Positioned(
                left: 201.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle65Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle66Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle67Widget1(),
              ),
              Positioned(
                left: 124.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCourierWidget1(),
              ),
              Positioned(
                left: 105.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 26.0,
                child: GeneratedSingerWidget1(),
              ),
              Positioned(
                left: 230.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle68Widget1(),
              ),
              Positioned(
                left: 247.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCarpenterWidget1(),
              ),
              Positioned(
                left: 232.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedBuilderWidget1(),
              ),
              Positioned(
                left: 201.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle69Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle70Widget1(),
              ),
              Positioned(
                left: 96.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle71Widget1(),
              ),
              Positioned(
                left: 124.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 26.0,
                child: GeneratedCoachWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 26.0,
                child: GeneratedConsuelorWidget1(),
              ),
              Positioned(
                left: 230.0,
                top: 565.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedRectangle72Widget1(),
              ),
              Positioned(
                left: 247.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 26.0,
                child: GeneratedActorressWidget1(),
              ),
              Positioned(
                left: 232.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 26.0,
                child: GeneratedPainterWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 803.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle55Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 818.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 33.0,
                child: GeneratedSELECTWidget(),
              )
            ]),
      ),
    ));
  }
}
