import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedRectangle53Widget11.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedMap1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedMyaccountWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedHOMEPAGEWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedAddserviceWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedMapWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedClipboard1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedRequest21Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedMessagesWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedRequestWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedComplain1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedUser51Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedJobsearch1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedTeamwork1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax2widget/generated/GeneratedSearchWidget1.dart';

/* Frame iPhone 11 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -3.0,
                top: 2.0,
                right: null,
                bottom: null,
                width: 417.0,
                height: 226.0,
                child: GeneratedRectangle53Widget11(),
              ),
              Positioned(
                left: 109.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 44.0,
                child: GeneratedHOMEPAGEWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 30.0,
                child: GeneratedMyaccountWidget(),
              ),
              Positioned(
                left: 231.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 127.0,
                height: 30.0,
                child: GeneratedAddserviceWidget(),
              ),
              Positioned(
                left: 66.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 33.0,
                child: GeneratedSearchWidget1(),
              ),
              Positioned(
                left: 258.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 33.0,
                child: GeneratedRequestWidget(),
              ),
              Positioned(
                left: 87.0,
                top: 845.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 33.0,
                child: GeneratedMapWidget(),
              ),
              Positioned(
                left: 253.0,
                top: 845.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 33.0,
                child: GeneratedMessagesWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 196.0,
                child: GeneratedTeamwork1Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedUser51Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedRequest21Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedJobsearch1Widget(),
              ),
              Positioned(
                left: 238.0,
                top: 292.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedClipboard1Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedMap1Widget(),
              ),
              Positioned(
                left: 237.0,
                top: 688.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedComplain1Widget(),
              )
            ]),
      ),
    ));
  }
}
