import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedADDSERVICEWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedRectangle30Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedACCEPTWidget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedRectangle53Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedRectangle53Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax21widget/generated/GeneratedSERVICESUCCESFULLYADDEDWidget.dart';

/* Frame iPhone 11 Pro Max - 21
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax21Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -50.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 254.0,
                child: GeneratedRectangle53Widget1(),
              ),
              Positioned(
                left: 97.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 44.0,
                child: GeneratedADDSERVICEWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 756.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 58.0,
                child: GeneratedRectangle30Widget1(),
              ),
              Positioned(
                left: 162.0,
                top: 771.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 33.0,
                child: GeneratedACCEPTWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 284.0,
                child: GeneratedRectangle53Widget2(),
              ),
              Positioned(
                left: 72.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 23.0,
                child: GeneratedSERVICESUCCESFULLYADDEDWidget(),
              )
            ]),
      ),
    ));
  }
}
