import 'package:flutter/material.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedREQUESTWidget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedUser32Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedNAMEWidget10.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedRectangle54Widget2.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedUser71Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedOnlineshoppingpana1Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedRectangle32Widget1.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedSERVICEWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedRectangle55Widget3.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedSERVICEINFOWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedTALKWidget.dart';
import 'package:flutterapp/diakoniaapp/generatediphone11promax8widget/generated/GeneratedCONTACTWidget.dart';

/* Frame iPhone 11 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -11.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 436.0,
                height: 431.0,
                child: GeneratedRectangle54Widget2(),
              ),
              Positioned(
                left: 11.0,
                top: 873.0,
                right: null,
                bottom: null,
                width: 384.0,
                height: 292.0,
                child: GeneratedRectangle32Widget1(),
              ),
              Positioned(
                left: 51.0,
                top: 804.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 154.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 78.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 33.0,
                child: GeneratedNAMEWidget10(),
              ),
              Positioned(
                left: 69.0,
                top: 824.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 46.0,
                child: GeneratedRectangle56Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 834.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 31.0,
                child: GeneratedTALKWidget(),
              ),
              Positioned(
                left: 215.0,
                top: 824.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 46.0,
                child: GeneratedRectangle55Widget3(),
              ),
              Positioned(
                left: 232.0,
                top: 834.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 31.0,
                child: GeneratedREQUESTWidget3(),
              ),
              Positioned(
                left: 126.0,
                top: 714.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 28.0,
                child: GeneratedSERVICEINFOWidget(),
              ),
              Positioned(
                left: 89.0,
                top: 529.0,
                right: null,
                bottom: null,
                width: 86.0,
                height: 26.0,
                child: GeneratedCONTACTWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 595.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 47.0,
                child: GeneratedSERVICEWidget(),
              ),
              Positioned(
                left: 361.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedUser32Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.12077294685990338;

                  final double height =
                      constraints.maxHeight * 0.05580357142857143;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10869565217391304,
                        y: constraints.maxHeight * 0.49107142857142855,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedUser71Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -53.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 750.0,
                height: 500.0,
                child: GeneratedOnlineshoppingpana1Widget(),
              )
            ]),
      ),
    ));
  }
}
